swagger: "2.0"
info:
  version: "0.0.1"
  title: Banka App
## during dev, should point to your local machine
host: localhost:5000
#basePath prefixes all resource paths
basePath: /api/v2
#
schemes:
  #tip: remove http to make production-grade
  - http
  - https
# formats of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    #binds a 127 app logic to a route
    x-swagger-router-controller: weclome_to_banka
    get:
      description: Returns Welcome to the banka
      # used as the method name of the controller
      operationId: welcome
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BankaWelcomeResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  BankaWelcomeResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string